### ISSUE TITLE
Can this be used to pull the current viewer count?

### ISSUE THREAD

**Issue by Larceniii** [unofficial-dlive-tv-api/dlivetv-unofficial-api-js#4]
**Is your feature request related to a problem? Please describe.**
I need to get the current viewer count on dlive, returned so I can add it to the current viewer count on youtube and add them together. I use restream.io

**Describe the solution you'd like**
I would like to be able to get the current viewer count to my html page that I am displaying on stream.

**Describe alternatives you've considered**
I've considered scraping the page using php every 3 mins or so.

**Additional context**
Not sure if this is even possible yet, just asking.

**Comment by timedotcc** [comment]
It will be available in the next version.

**Comment by timedotcc** [comment]
Its now available.
```js
example.getChannelViewers('FearBumper76' /* enter a displayname, not the Blockchain username */).then((result) => {
  console.log(result)
}).catch((error) => {
  console.log(error)
})
```

**Comment by Larceniii** [comment]
Thank you so much!

**Comment by timedotcc** [comment]
I don't know. I don't want to spread any rumours here.
