### ISSUE TITLE
Feature request: get channel followers

### ISSUE THREAD

**Issue by Banonevar** [unofficial-dlive-tv-api/dlivetv-unofficial-api-js#6]
**Is your feature request related to a problem? Please describe.**
I suggest implement function for get channel followers

**Describe the solution you'd like**
I want get channel followers with paginations, e.t.c

**Describe alternatives you've considered**
Guess i need describe how it can be done? Ok.
We need POST to `https://graphigo.prd.dlive.tv/`
With some example payload:
``
{"operationName":"LivestreamProfileFollowers","variables":{"displayname":"PewDiePie","sortedBy":"AZ","first":20,"isLoggedIn":true},"query":"query LivestreamProfileFollowers($displayname: String!, $sortedBy: RelationSortOrder, $first: Int, $after: String, $isLoggedIn: Boolean!) {\n  userByDisplayName(displayname: $displayname) {\n    id\n    displayname\n    followers(sortedBy: $sortedBy, first: $first, after: $after) {\n      pageInfo {\n        endCursor\n        hasNextPage\n        __typename\n      }\n      list {\n        ...VDliveAvatarFrag\n        ...VDliveNameFrag\n        ...VFollowFrag\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment VDliveAvatarFrag on User {\n  avatar\n  __typename\n}\n\nfragment VDliveNameFrag on User {\n  displayname\n  partnerStatus\n  __typename\n}\n\nfragment VFollowFrag on User {\n  id\n  username\n  displayname\n  isFollowing @include(if: $isLoggedIn)\n  isMe @include(if: $isLoggedIn)\n  followers {\n    totalCount\n    __typename\n  }\n  __typename\n}\n"}
``
it will return first 20 followers (if we noot use pagination here).

**Additional context**
Example response from dlive:
`{"data":{"userByDisplayName":{"id":"user:pdp","displayname":"PewDiePie","followers":{"pageInfo":{"endCursor":"19","hasNextPage":true,"__typename":"PageInfo"},"list":[{"avatar":"https://images.prd.dlivecdn.com/avatar/default6.png","__typename":"User","displayname":"RektByKeltic","partnerStatus":"NONE","id":"user:a-keltic-knight","username":"a-keltic-knight","isFollowing":false,"isMe":false,"followers":{"totalCount":233,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/default23.png","__typename":"User","displayname":"A-l-t-a-n","partnerStatus":"NONE","id":"user:a-l-t-a-n","username":"a-l-t-a-n","isFollowing":false,"isMe":false,"followers":{"totalCount":91,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/d4092f63-6074-11e9-86d2-8a81961f24ea","__typename":"User","displayname":"JohnyBlaze23","partnerStatus":"NONE","id":"user:a-z9","username":"a-z9","isFollowing":false,"isMe":false,"followers":{"totalCount":77,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/6097cbdf-5bea-11e9-ab17-865634f95b6b","__typename":"User","displayname":"Lady_AkSoY","partnerStatus":"NONE","id":"user:a.aksoy","username":"a.aksoy","isFollowing":false,"isMe":false,"followers":{"totalCount":241,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/58aa3fd8-531e-11e9-8ff5-de98b5d4a7b7","__typename":"User","displayname":"A.BahaYURDAKUL67","partnerStatus":"NONE","id":"user:a.bahayurdakul67","username":"a.bahayurdakul67","isFollowing":false,"isMe":false,"followers":{"totalCount":128,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/40f04227-e9c5-11e8-8615-16c837aff608","__typename":"User","displayname":"r3wella","partnerStatus":"VERIFIED_PARTNER","id":"user:a.emin1","username":"a.emin1","isFollowing":false,"isMe":false,"followers":{"totalCount":1105,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/63fe28ea-4f53-11e9-901d-66540b9c68b7","__typename":"User","displayname":"A.O.N.FiFA","partnerStatus":"NONE","id":"user:a.o.n.fifa","username":"a.o.n.fifa","isFollowing":false,"isMe":false,"followers":{"totalCount":318,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/7171493d-65f0-11e9-818d-ce0b21b6aee2","__typename":"User","displayname":"RD_a.rza","partnerStatus":"NONE","id":"user:a.rza","username":"a.rza","isFollowing":false,"isMe":false,"followers":{"totalCount":437,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/thumbnail/f1b8ecec-33b0-11e9-9f23-8ec705f1dd1b","__typename":"User","displayname":"SinfulWolf","partnerStatus":"NONE","id":"user:a.s.a","username":"a.s.a","isFollowing":false,"isMe":false,"followers":{"totalCount":326,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/38e33e6f-62bc-11e9-bc94-460601ac0a66","__typename":"User","displayname":"A11GreyWolf","partnerStatus":"NONE","id":"user:a11greywolf","username":"a11greywolf","isFollowing":false,"isMe":false,"followers":{"totalCount":17,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/default23.png","__typename":"User","displayname":"A1Normal2Person","partnerStatus":"NONE","id":"user:a1normal2person","username":"a1normal2person","isFollowing":false,"isMe":false,"followers":{"totalCount":126,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/default1.png","__typename":"User","displayname":"3arda4","partnerStatus":"NONE","id":"user:a1rda","username":"a1rda","isFollowing":false,"isMe":false,"followers":{"totalCount":133,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/a59e314f-5b19-11e9-9e77-5295f8b3e9d1","__typename":"User","displayname":"A320","partnerStatus":"NONE","id":"user:a320","username":"a320","isFollowing":false,"isMe":false,"followers":{"totalCount":300,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/757fd21c-66b1-11e9-818d-ce0b21b6aee2","__typename":"User","displayname":"A3VAN","partnerStatus":"NONE","id":"user:a3van","username":"a3van","isFollowing":false,"isMe":false,"followers":{"totalCount":0,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/default17.png","__typename":"User","displayname":"a5medtalz","partnerStatus":"NONE","id":"user:a5medtalz","username":"a5medtalz","isFollowing":false,"isMe":false,"followers":{"totalCount":30,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/default2.png","__typename":"User","displayname":"ductran","partnerStatus":"NONE","id":"user:aa15","username":"aa15","isFollowing":false,"isMe":false,"followers":{"totalCount":130,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/default12.png","__typename":"User","displayname":"quyn","partnerStatus":"NONE","id":"user:aa4","username":"aa4","isFollowing":false,"isMe":false,"followers":{"totalCount":107,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/default17.png","__typename":"User","displayname":"coolboyo","partnerStatus":"NONE","id":"user:aaaaa123123","username":"aaaaa123123","isFollowing":false,"isMe":false,"followers":{"totalCount":161,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/39326f2c-4b46-11e9-97f0-0eb3a818c822","__typename":"User","displayname":"aaakwiwjd","partnerStatus":"NONE","id":"user:aaakwiwjd","username":"aaakwiwjd","isFollowing":false,"isMe":false,"followers":{"totalCount":13,"__typename":"UserConnection"}},{"avatar":"https://images.prd.dlivecdn.com/avatar/default2.png","__typename":"User","displayname":"aabr","partnerStatus":"NONE","id":"user:aabr","username":"aabr","isFollowing":false,"isMe":false,"followers":{"totalCount":2,"__typename":"UserConnection"}}],"__typename":"UserConnection"},"__typename":"User"}}}`

**Comment by Carbowix** [comment]
Implemented in next update, thanks for your suggestion
